import { POPULAR_BUILDINGS } from '../buildingDefs';
import { extractStreet } from './streets';
import { hashSeed, mulberry32, offsetPoint, type LatLng } from './geometry';
import { hasDistrict, pointAllowed, randomAllowedPoint, wardKey } from './areas';
import COORDS from './coords.json';

export const PRECISION = { building: 0, street: 1, ward: 2, district: 3, nearBuilding: 4 } as const;
export type Precision = 0 | 1 | 2 | 3 | 4;

/** Generated by scripts/build-geo-coords.ts. Ward keys are "<District>|<normalized ward>",
 *  street keys "<District>|<street key>", building keys the BuildingDef name. */
export interface GeoCoords {
  buildings: Record<string, LatLng>;
  wards: Record<string, LatLng>;
  streets: Record<string, LatLng>;
  /** Names the geocoder tried and could not place — skipped on re-runs. */
  misses: string[];
}

/** `geoArea` is the ward key the pin is confined to ('' = just its district), so the
 *  map's overlap nudging (client side) keeps it there too. */
export interface Placement { geo: [number, number, Precision]; geoLabel: string; geoArea: string }

// How far listings sharing one anchor are spread, so their pins don't sit on
// top of each other. Scaled to how big the anchor really is.
const SPREAD_M = { building: 30, nearBuilding: 300, street: 150, ward: 350, district: 500 };

// Places pinned by verified address (Blake, 2026-09-26): map-only, so unlike
// POPULAR_BUILDINGS they don't create a building page or a "Popular buildings" card.
// spreadM is roughly the grounds' size. `near: true` = a landmark people live NEAR,
// never in (parks, malls, resorts): always labelled "Near …".
// Coordinates are OpenStreetMap features whose name/address matched — don't add a
// place without that check: fuzzy geocoding put "Sam Towers" on Meridian Towers.
const MAP_LANDMARKS: { name: string; pattern: RegExp; at: LatLng; spreadM: number; near?: boolean }[] = [
  // Fusion Resort & Villas, Trường Sa, Ngũ Hành Sơn. Fusion Suites is a different hotel on Vo Nguyen Giap.
  { name: 'Fusion Resort & Villas', pattern: /\bfusion\b(?!\s+suites?)/i, at: [15.97242, 108.28229], spreadM: 150 },
  // Premier Village Resort, 99 Võ Nguyên Giáp (villas for rent inside it).
  { name: 'Premier Village', pattern: /\bprem(?:ier|eir)\s+village\b/i, at: [16.04362, 108.24966], spreadM: 150 },
  // Chung cư Monarchy, 535 Trần Hưng Đạo, An Hải.
  { name: 'Monarchy', pattern: /\bmonarchy\b/i, at: [16.05484, 108.23297], spreadM: 40 },
  // Euro Village / Làng Châu Âu villa compound, Trần Hưng Đạo, Sơn Trà.
  { name: 'Euro Village', pattern: /\beuro\s*vill(?:age|a)\b|làng châu âu/i, at: [16.05432, 108.23111], spreadM: 200 },
  // The Ori Garden, Liên Chiểu.
  { name: 'The Ori Garden', pattern: /\bori\s+garden\b/i, at: [16.10009, 108.12951], spreadM: 60 },
  // Wyndham Danang Golden Bay, 01 Lê Văn Duyệt, Sơn Trà.
  { name: 'Golden Bay', pattern: /\bgolden\s*bay\b/i, at: [16.09806, 108.22438], spreadM: 40 },
  { name: 'Mikazuki', pattern: /\bmikazuki\b/i, at: [16.09358, 108.14436], spreadM: 150, near: true },
  { name: 'Furama Resort', pattern: /\bfurama\b/i, at: [16.03975, 108.25134], spreadM: 150, near: true },
  // Asia Park, since renamed Sun World Danang Wonders / Da Nang Downtown.
  { name: 'Asia Park', pattern: /\basia\s+park\b|danang\s+wonders|da\s*nang\s+downtown/i, at: [16.04122, 108.22639], spreadM: 300, near: true },
  { name: 'Vincom Plaza', pattern: /\bvincom\b/i, at: [16.07136, 108.23026], spreadM: 300, near: true },
  { name: 'APEC Park', pattern: /\bapec\s+park\b|công viên apec/i, at: [16.05875, 108.22351], spreadM: 300, near: true },
  { name: 'East Sea Park', pattern: /\beast\s+sea\s+park\b|công viên biển đông/i, at: [16.06835, 108.24593], spreadM: 300, near: true },
];

// "Garden house near Hyatt Regency" is not IN the Hyatt. A building name right after
// one of these phrases places the pin around the building, labelled "Near …".
const NEAR_BEFORE = /(?:near|close to|next to|opposite|across from|behind|walk(?:ing)?(?: distance)? (?:to|from)|minutes? (?:walk )?(?:to|from)|steps (?:to|from)|gần|cạnh|đối diện)\s+(?:the\s+)?$/i;

// Anchors for spreading pins we can't place precisely: the known street/ward points
// inside the region, i.e. where that area's listings actually are.
const anchorCache = new WeakMap<GeoCoords, Map<string, LatLng[]>>();
function anchors(coords: GeoCoords, district: string, ward: string | null): LatLng[] {
  let byRegion = anchorCache.get(coords);
  if (!byRegion) { byRegion = new Map(); anchorCache.set(coords, byRegion); }
  const key = ward ?? district;
  let found = byRegion.get(key);
  if (!found) {
    const prefix = `${district}|`;
    found = [...Object.entries(coords.streets), ...Object.entries(coords.wards)]
      .filter(([k, p]) => k.startsWith(prefix) && pointAllowed(p, district, ward))
      .map(([, p]) => p);
    byRegion.set(key, found);
  }
  return found;
}

const round5 = (n: number) => Math.round(n * 1e5) / 1e5;

/** Where a listing goes on the map: the most precise location its data supports —
 *  always inside its district, inside its ward when we know it, and never on water
 *  (Blake, 2026-09-26). */
export function placeListing(
  l: { slug: string; district: string; neighborhood: string; title: string; text: string },
  coords: GeoCoords = COORDS as unknown as GeoCoords,
): Placement | null {
  if (!hasDistrict(l.district)) return null;            // covers '' and 'Not Provided'
  const district = l.district;
  const ward = wardKey(district, l.neighborhood);
  // Checks run on the ROUNDED point — the one that ships — so rounding can't nudge
  // a pin by the riverbank into the river.
  const r5 = ([lat, lng]: LatLng): LatLng => [round5(lat), round5(lng)];
  const ok = (p: LatLng) => pointAllowed(r5(p), district, ward);
  const inDistrict = (p: LatLng) => pointAllowed(r5(p), district, null);
  // randomAllowedPoint, retried until its rounded point still obeys the rule.
  const anywhere = (w: string | null, test: (p: LatLng) => boolean) => {
    for (let i = 0; i < 8; i++) { const p = randomAllowedPoint(district, w, hashSeed(`${l.slug}~${i}`)); if (p && test(p)) return p; }
    return null;
  };
  const seed = hashSeed(l.slug);
  const hay = `${l.title} ${l.text}`;
  const place = ([lat, lng]: LatLng, p: Precision, label: string, area = ward ?? ''): Placement =>
    ({ geo: [round5(lat), round5(lng), p], geoLabel: label, geoArea: area });

  // A seeded spot around an anchor that obeys the rules; the anchor itself if none does.
  const around = (anchor: LatLng, radiusM: number, salt = ''): LatLng | null => {
    for (let i = 0; i < 12; i++) {
      const p = offsetPoint(anchor, hashSeed(`${l.slug}${salt}#${i}`), radiusM);
      if (ok(p)) return p;
    }
    return ok(anchor) ? anchor : null;
  };

  const landmark = MAP_LANDMARKS.find(m => m.pattern.test(hay) && ok(m.at));
  if (landmark) {
    const idx = hay.search(landmark.pattern);
    const near = landmark.near || NEAR_BEFORE.test(hay.slice(Math.max(0, idx - 40), idx));
    const p = around(landmark.at, near ? Math.max(SPREAD_M.nearBuilding, landmark.spreadM) : landmark.spreadM);
    if (p) return place(p, near ? PRECISION.nearBuilding : PRECISION.building, landmark.name);
  }

  // A building or street only counts when its own point obeys the rules: outside the
  // ward or district means the listing's data or the mention is wrong.
  const building = POPULAR_BUILDINGS.find(b => b.pattern.test(hay) && coords.buildings[b.name] && ok(coords.buildings[b.name]));
  if (building) {
    const at = coords.buildings[building.name];
    const idx = hay.search(building.pattern);
    const near = NEAR_BEFORE.test(hay.slice(Math.max(0, idx - 40), idx));
    const p = around(at, near ? SPREAD_M.nearBuilding : SPREAD_M.building);
    if (p) return place(p, near ? PRECISION.nearBuilding : PRECISION.building, building.name);
  }

  const street = extractStreet(hay);
  const streetAt = street && coords.streets[`${district}|${street.key}`];
  if (street && streetAt && ok(streetAt)) {
    const p = around(streetAt, SPREAD_M.street);
    if (p) return place(p, PRECISION.street, street.name);
  }

  // Ward, then district: spread around where that area's listings are, else anywhere
  // allowed in it.
  const spread = (list: LatLng[], radiusM: number): LatLng | null => {
    if (!list.length) return null;
    const rnd = mulberry32(seed);
    for (let i = 0; i < 6; i++) {
      const p = around(list[Math.floor(rnd() * list.length)], radiusM, `a${i}`);
      if (p) return p;
    }
    return null;
  };
  if (ward) {
    const p = spread(anchors(coords, district, ward), SPREAD_M.ward) ?? anywhere(ward, ok);
    if (p) return place(p, PRECISION.ward, l.neighborhood);
  }
  // District level: the rule is just "in the district, not on water".
  const list = anchors(coords, district, null);
  if (list.length) {
    const rnd = mulberry32(seed);
    for (let i = 0; i < 6; i++) {
      const a = list[Math.floor(rnd() * list.length)];
      for (let j = 0; j < 12; j++) {
        const p = offsetPoint(a, hashSeed(`${l.slug}d${i}#${j}`), SPREAD_M.district);
        if (inDistrict(p)) return place(p, PRECISION.district, '', '');
      }
    }
  }
  const p = anywhere(null, inDistrict);
  return p ? place(p, PRECISION.district, '', '') : null;
}
