import { POPULAR_BUILDINGS } from '../buildingDefs';
import { DISTRICT_BOUNDARIES } from '../districtBoundaries';
import { extractStreet, normalizeName } from './streets';
import type { Geometry } from 'geojson';
import { hashSeed, mainPart, mulberry32, offsetPoint, pointInGeometry, randomPointIn, type LatLng } from './geometry';
import COORDS from './coords.json';

export const PRECISION = { building: 0, street: 1, ward: 2, district: 3, nearBuilding: 4 } as const;
export type Precision = 0 | 1 | 2 | 3 | 4;

/** Generated by scripts/build-geo-coords.ts. Ward keys are "<District>|<normalized ward>",
 *  street keys "<District>|<street key>", building keys the BuildingDef name. */
export interface GeoCoords {
  buildings: Record<string, LatLng>;
  wards: Record<string, LatLng>;
  streets: Record<string, LatLng>;
  /** Names the geocoder tried and could not place — skipped on re-runs. */
  misses: string[];
}

export interface Placement { geo: [number, number, Precision]; geoLabel: string }

// How far listings sharing one anchor are spread, so their pins don't sit on
// top of each other. Scaled to how big the anchor really is.
const SPREAD_M = { building: 30, nearBuilding: 300, street: 150, ward: 350, district: 500 };

// "Garden house near Hyatt Regency" is not IN the Hyatt. A building name right after
// one of these phrases places the pin around the building, labelled "Near …".
const NEAR_BEFORE = /(?:near|close to|next to|opposite|across from|behind|walk(?:ing)?(?: distance)? (?:to|from)|minutes? (?:walk )?(?:to|from)|steps (?:to|from)|gần|cạnh|đối diện)\s+(?:the\s+)?$/i;

// District-only listings are spread around the district's KNOWN listing locations
// (its geocoded streets and wards), not uniformly over its boundary: most of Son
// Tra's polygon is forested mountain, Lien Chieu's runs up the Hai Van pass, and
// Hoi An's includes the Cham Islands. Uniform scatter put pins in all of those.
const anchorCache = new WeakMap<GeoCoords, Map<string, LatLng[]>>();
function districtAnchors(coords: GeoCoords, district: string, boundary: Geometry): LatLng[] {
  let byDistrict = anchorCache.get(coords);
  if (!byDistrict) { byDistrict = new Map(); anchorCache.set(coords, byDistrict); }
  let anchors = byDistrict.get(district);
  if (!anchors) {
    const prefix = `${district}|`;
    anchors = [...Object.entries(coords.streets), ...Object.entries(coords.wards)]
      .filter(([k, p]) => k.startsWith(prefix) && pointInGeometry(p, boundary))
      .map(([, p]) => p);
    byDistrict.set(district, anchors);
  }
  return anchors;
}

function districtPoint(slug: string, seed: number, boundary: Geometry, anchors: LatLng[]): LatLng {
  if (!anchors.length) return randomPointIn(mainPart(boundary), seed);
  const rnd = mulberry32(seed);
  let anchor = anchors[0];
  for (let i = 0; i < 8; i++) {
    anchor = anchors[Math.floor(rnd() * anchors.length)];
    const p = offsetPoint(anchor, hashSeed(`${slug}#${i}`), SPREAD_M.district);
    if (pointInGeometry(p, boundary)) return p;   // offsets near the coast can land in the sea
  }
  return anchor;
}

const round5 = (n: number) => Math.round(n * 1e5) / 1e5;
const place = ([lat, lng]: LatLng, p: Precision, label: string): Placement =>
  ({ geo: [round5(lat), round5(lng), p], geoLabel: label });

/** Where a listing goes on the map: the most precise location its data supports. */
export function placeListing(
  l: { slug: string; district: string; neighborhood: string; title: string; text: string },
  coords: GeoCoords = COORDS as unknown as GeoCoords,
): Placement | null {
  const boundary = DISTRICT_BOUNDARIES[l.district];
  if (!boundary) return null;            // covers '' and 'Not Provided'
  const seed = hashSeed(l.slug);
  const hay = `${l.title} ${l.text}`;

  // Same rule as streets: a building outside the listing's own district means the
  // district or the mention is wrong, so it doesn't get to move the pin.
  const building = POPULAR_BUILDINGS.find(b =>
    b.pattern.test(hay) && coords.buildings[b.name] && pointInGeometry(coords.buildings[b.name], boundary));
  if (building) {
    const at = coords.buildings[building.name];
    const idx = hay.search(building.pattern);
    const near = NEAR_BEFORE.test(hay.slice(Math.max(0, idx - 40), idx));
    return near
      ? place(offsetPoint(at, seed, SPREAD_M.nearBuilding), PRECISION.nearBuilding, building.name)
      : place(offsetPoint(at, seed, SPREAD_M.building), PRECISION.building, building.name);
  }

  // Street and ward coordinates must sit inside the listing's own district: that is
  // what stops a same-named street elsewhere in the city from pulling the pin over.
  const street = extractStreet(hay);
  const streetAt = street && coords.streets[`${l.district}|${street.key}`];
  if (street && streetAt && pointInGeometry(streetAt, boundary)) {
    return place(offsetPoint(streetAt, seed, SPREAD_M.street), PRECISION.street, street.name);
  }

  const wardAt = l.neighborhood && coords.wards[`${l.district}|${normalizeName(l.neighborhood)}`];
  if (wardAt && pointInGeometry(wardAt, boundary)) {
    return place(offsetPoint(wardAt, seed, SPREAD_M.ward), PRECISION.ward, l.neighborhood);
  }

  return place(districtPoint(l.slug, seed, boundary, districtAnchors(coords, l.district, boundary)), PRECISION.district, '');
}
